[package]
name = "gelbooru-api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
hyper = "0.14"
hyper-rustls = "0.23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
